language:
  - cpp

sudo:
  - false

os:
  - linux
  - osx

dist:
  - xenial

compiler:
  - clang

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest -C unit --output-on-failure
  - ctest -C perf --verbose

